export default [ { id: 410,
    name: 'Est a sed lorem elit luctus sit',
    description:
     'Elit. Adipiscing elit interdum mi gravida tellus non sem dolor egestas in. Nibh adipiscing porttitor dolor adipiscing tellus sit sit egestas cursus ac.',
    tags: [ 'mi' ],
    access: [ 'everyone' ],
    lastViewed: '2012/03/13',
    expirationDate: '2019/02/25',
    icon: '<i class=\'fa fa-2x fa-file-alt\'></i>' },
  { id: 827,
    name: 'Turpis mollis ut elit',
    description:
     'Ut in gravida dolor est sed tincidunt adipiscing elit commodo quam. Sit ipsum praesent lorem dolor gravida non adipiscing consectetur nunc. Eu. Nulla elit in luctus rhoncus elit a bibendum turpis nulla quam lorem.',
    tags: [ 'praesent' ],
    access: [ 'samantha' ],
    lastViewed: '2014/03/06',
    expirationDate: '2019/01/11',
    icon: '<i class=\'fa fa-2x fa-file-excel\'></i>' },
  { id: 254,
    name: 'Amet adipiscing rhoncus vivamus elit',
    description:
     'Nunc eu feugiat a turpis in venenatis. Gravida in lorem non luctus nibh sollicitudin. Commodo placerat dolor. Dolor a ipsum interdum consectetur adipiscing elit sollicitudin sem turpis nunc lorem turpis elit. Sit in mi elit mollis amet porttitor elit adipiscing.',
    tags: [ 'et' ],
    access: [ 'mike' ],
    lastViewed: '2015/12/16',
    expirationDate: '2019/04/12',
    icon: '<i class=\'fa fa-2x fa-file-word\'></i>' },
  { id: 500,
    name: 'Amet placerat a tellus in nunc',
    description:
     'Adipiscing. Dolor adipiscing interdum porttitor venenatis mollis nunc placerat. Adipiscing interdum mi consectetur sit a non augue cursus tellus elit dolor eu ac. Elit ut interdum sem quam. Ac amet sed venenatis mollis augue ut a elit gravida interdum amet adipiscing interdum.',
    tags: [],
    access: [ 'everyone' ],
    lastViewed: '2012/06/02',
    expirationDate: '2019/02/07',
    icon: '<i class=\'fa fa-2x fa-file-word\'></i>' },
  { id: 390,
    name: 'Consectetur venenatis a elit interdum nulla eu',
    description:
     'Mollis ac augue dolor nunc elit porttitor amet. Tellus praesent mollis tincidunt augue nibh quam in ipsum luctus sit amet mi. Lorem amet gravida gravida consectetur a tellus est porttitor dolor tincidunt commodo. Nibh turpis est elit bibendum mollis ipsum amet vivamus praesent sed elit. Gravida sed bibendum interdum venenatis turpis.',
    tags: [ 'lorem' ],
    access: [ 'joe' ],
    lastViewed: '2015/08/24',
    expirationDate: '2019/06/10',
    icon: '<i class=\'fa fa-2x fa-file-excel\'></i>' },
  { id: 386,
    name: 'Turpis elit non sollicitudin a',
    description:
     'Elit elit elit amet adipiscing adipiscing ut ut mi. Turpis sit interdum egestas mollis sit adipiscing ac sem gravida elit quam elit. Adipiscing ac lorem dolor adipiscing sed adipiscing nulla luctus in praesent in cursus feugiat venenatis.',
    tags: [ 'elit', 'amet' ],
    access: [ 'joe' ],
    lastViewed: '2015/12/11',
    expirationDate: '2019/01/27',
    icon: '<i class=\'fa fa-2x fa-file-excel\'></i>' },
  { id: 801,
    name: 'Sollicitudin est',
    description:
     'Interdum nulla vivamus nibh ut ut sem a placerat augue. Bibendum tincidunt venenatis turpis rhoncus. Nulla luctus sem. Adipiscing in a bibendum sollicitudin mi lorem.',
    tags: [],
    access: [ 'everyone' ],
    lastViewed: '2014/07/01',
    expirationDate: '2019/12/05',
    icon: '<i class=\'fa fa-2x fa-file-alt\'></i>' },
  { id: 216,
    name: 'Elit ut lorem commodo elit',
    description:
     'In dolor ac sollicitudin elit. Dolor vivamus in ut ut et interdum elit amet sit. Tincidunt amet eu nunc a interdum cursus. Ut placerat venenatis tincidunt elit. Et dolor ipsum a egestas.',
    tags: [],
    access: [ 'samantha' ],
    lastViewed: '2015/09/23',
    expirationDate: '2019/05/09',
    icon: '<i class=\'fa fa-2x fa-file-word\'></i>' },
  { id: 87,
    name: 'Consectetur tellus amet ut lorem bibendum rhoncus',
    description:
     'Mi est elit adipiscing. Ut mi nulla nulla dolor eu adipiscing non placerat adipiscing sem praesent a. Sit a elit adipiscing sed elit eu ut rhoncus egestas ac turpis. Ac.',
    tags: [],
    access: [ 'everyone' ],
    lastViewed: '2013/09/07',
    expirationDate: '2019/08/11',
    icon: '<i class=\'fa fa-2x fa-file-alt\'></i>' },
  { id: 736,
    name: 'Adipiscing ut in quam rhoncus',
    description:
     'Ut placerat adipiscing. Tellus rhoncus ut lorem porttitor venenatis adipiscing amet eu elit gravida elit in.',
    tags: [ 'egestas' ],
    access: [ 'mike' ],
    lastViewed: '2012/03/12',
    expirationDate: '2019/02/12',
    icon: '<i class=\'fa fa-2x fa-file-alt\'></i>' },
  { id: 722,
    name: 'Nunc elit',
    description:
     'Lorem nulla ut cursus dolor a interdum mollis porttitor et sed egestas adipiscing amet elit. Ut interdum bibendum amet tellus nunc mollis elit luctus sit elit praesent. Amet rhoncus commodo eu augue interdum lorem praesent adipiscing in ut elit porttitor. Nunc. A elit lorem turpis ac rhoncus venenatis tellus sit feugiat placerat. Elit sollicitudin cursus vivamus ipsum porttitor.',
    tags: [],
    access: [ 'joe' ],
    lastViewed: '2015/02/13',
    expirationDate: '2019/03/07',
    icon: '<i class=\'fa fa-2x fa-file-word\'></i>' },
  { id: 241,
    name: 'Gravida interdum elit',
    description:
     'Ut bibendum ac dolor egestas commodo sit nulla elit augue adipiscing amet tellus nibh ut. Amet nulla sit. Non placerat ut mollis in in nulla elit turpis dolor amet a sed egestas porttitor. Adipiscing sit nunc augue adipiscing elit nulla ipsum gravida tellus gravida mi. Nibh nunc ut et eu amet bibendum adipiscing.',
    tags: [ 'in' ],
    access: [ 'everyone' ],
    lastViewed: '2017/10/10',
    expirationDate: '2019/09/04',
    icon: '<i class=\'fa fa-2x fa-file-excel\'></i>' },
  { id: 554,
    name: 'Ut mollis adipiscing',
    description:
     'Vivamus gravida dolor elit sit elit praesent nulla et adipiscing non lorem turpis egestas gravida. Mi nunc gravida mollis egestas sed nulla feugiat sit ac interdum in amet consectetur tellus. Placerat elit vivamus cursus gravida commodo adipiscing ut adipiscing. A sit dolor in elit.',
    tags: [ 'sem' ],
    access: [ 'mike' ],
    lastViewed: '2015/01/13',
    expirationDate: '2019/08/02',
    icon: '<i class=\'fa fa-2x fa-file-word\'></i>' },
  { id: 485,
    name: 'Nibh sit augue est',
    description:
     'Nibh sem turpis. Dolor nunc mi feugiat tincidunt. Vivamus elit. Mollis elit bibendum quam porttitor elit gravida adipiscing sem feugiat consectetur sit turpis augue. Nulla dolor interdum tellus ut nibh sem in gravida sollicitudin sit ipsum ut mi.',
    tags: [ 'elit', 'elit' ],
    access: [ 'samantha' ],
    lastViewed: '2015/12/19',
    expirationDate: '2019/03/21',
    icon: '<i class=\'fa fa-2x fa-file-word\'></i>' },
  { id: 578,
    name: 'Luctus ac bibendum',
    description:
     'Ut nulla elit sollicitudin est turpis a a. Rhoncus cursus ut est dolor.',
    tags: [ 'adipiscing', 'sem' ],
    access: [ 'mike' ],
    lastViewed: '2018/02/08',
    expirationDate: '2019/12/23',
    icon: '<i class=\'fa fa-2x fa-file-word\'></i>' },
  { id: 429,
    name: 'Elit nibh ut adipiscing ut',
    description:
     'Nulla consectetur lorem a. Nunc sollicitudin consectetur nulla in vivamus commodo lorem dolor ut tellus adipiscing. Venenatis a in egestas elit sollicitudin elit adipiscing porttitor adipiscing amet ipsum in dolor. Rhoncus nunc tellus mollis ut interdum sem. Commodo turpis et nibh in in elit feugiat interdum praesent dolor eu adipiscing lorem.',
    tags: [ 'praesent', 'bibendum' ],
    access: [ 'samantha' ],
    lastViewed: '2017/05/27',
    expirationDate: '2019/02/26',
    icon: '<i class=\'fa fa-2x fa-file-powerpoint\'></i>' },
  { id: 647,
    name: 'Vivamus lorem a',
    description:
     'Ut mollis rhoncus porttitor gravida lorem lorem tincidunt ut adipiscing. Quam. Lorem sollicitudin amet sit quam venenatis gravida dolor sed gravida ipsum in. Turpis placerat quam mollis ut a augue ac amet sollicitudin turpis est sed eu adipiscing. Nulla elit tellus cursus sit porttitor a commodo elit praesent interdum mollis egestas lorem sit. Cursus ut elit ipsum elit sed turpis in adipiscing adipiscing tincidunt mi consectetur. Ut porttitor in quam.',
    tags: [ 'nibh', 'adipiscing', 'commodo' ],
    access: [ 'samantha' ],
    lastViewed: '2013/06/08',
    expirationDate: '2019/12/31',
    icon: '<i class=\'fa fa-2x fa-file-word\'></i>' },
  { id: 753,
    name: 'Ipsum tellus elit feugiat ac',
    description:
     'Gravida dolor interdum turpis tellus elit nibh elit luctus mollis interdum. Adipiscing. Est venenatis praesent nunc interdum elit non ut turpis elit. Adipiscing nulla. Ipsum consectetur amet elit praesent sollicitudin sed turpis elit sit adipiscing. Sollicitudin augue consectetur ut praesent bibendum. Luctus gravida placerat et.',
    tags: [ 'adipiscing', 'cursus', 'ut' ],
    access: [ 'samantha' ],
    lastViewed: '2016/04/26',
    expirationDate: '2019/04/04',
    icon: '<i class=\'fa fa-2x fa-file-word\'></i>' },
  { id: 824,
    name: 'Turpis bibendum turpis nibh et',
    description:
     'Amet est lorem ut sollicitudin luctus praesent in tellus in. Nulla nunc quam sit interdum in dolor eu amet turpis est venenatis ut placerat adipiscing.',
    tags: [ 'quam', 'lorem', 'amet' ],
    access: [ 'everyone' ],
    lastViewed: '2014/04/15',
    expirationDate: '2019/11/05',
    icon: '<i class=\'fa fa-2x fa-file-word\'></i>' },
  { id: 744,
    name: 'Mi nulla ut luctus ipsum turpis nulla',
    description:
     'Mi lorem tellus sollicitudin gravida in sit. Turpis in ipsum porttitor. Nulla et egestas consectetur ut lorem in mollis commodo. Amet elit turpis adipiscing nulla sit quam dolor ac lorem sem in rhoncus. Elit adipiscing mi. Non lorem porttitor praesent interdum tellus elit amet commodo elit turpis. Elit elit est adipiscing quam mollis sollicitudin porttitor amet in turpis eu rhoncus elit a.',
    tags: [ 'nibh', 'porttitor', 'et' ],
    access: [ 'samantha' ],
    lastViewed: '2013/03/27',
    expirationDate: '2019/06/12',
    icon: '<i class=\'fa fa-2x fa-file-alt\'></i>' },
  { id: 335,
    name: 'In lorem sem eu interdum',
    description:
     'Adipiscing turpis tellus adipiscing adipiscing in gravida adipiscing luctus nulla rhoncus ut ut. Est in a mi a amet dolor. Praesent nunc a egestas elit tellus elit nulla amet. Elit quam amet nibh nunc tellus ut. Quam praesent amet cursus lorem augue ut praesent in. Nulla elit bibendum ut cursus ac sem dolor gravida vivamus nibh a adipiscing. In placerat bibendum tellus mollis venenatis.',
    tags: [],
    access: [ 'joe' ],
    lastViewed: '2016/10/15',
    expirationDate: '2019/02/08',
    icon: '<i class=\'fa fa-2x fa-file-alt\'></i>' },
  { id: 616,
    name: 'Mollis lorem luctus feugiat sed',
    description:
     'Porttitor rhoncus praesent in est interdum a. Bibendum ipsum gravida nibh elit egestas sed a feugiat rhoncus consectetur adipiscing. Venenatis augue non dolor consectetur placerat turpis bibendum a. Gravida feugiat sit.',
    tags: [ 'interdum', 'sed', 'bibendum' ],
    access: [ 'samantha' ],
    lastViewed: '2018/09/04',
    expirationDate: '2019/11/04',
    icon: '<i class=\'fa fa-2x fa-file-powerpoint\'></i>' },
  { id: 237,
    name: 'Luctus tincidunt elit nulla mi adipiscing',
    description:
     'Lorem sit porttitor egestas placerat praesent rhoncus cursus. Luctus tincidunt ipsum interdum. Elit ipsum quam eu tincidunt nulla ac praesent venenatis. Gravida ut lorem adipiscing consectetur.',
    tags: [ 'interdum', 'sed', 'adipiscing' ],
    access: [ 'joe' ],
    lastViewed: '2019/10/07',
    expirationDate: '2019/02/13',
    icon: '<i class=\'fa fa-2x fa-file-excel\'></i>' },
  { id: 773,
    name: 'Sed nulla feugiat turpis',
    description:
     'Lorem adipiscing nibh in nunc nulla et. Quam dolor adipiscing sollicitudin ut.',
    tags: [],
    access: [ 'everyone' ],
    lastViewed: '2018/05/12',
    expirationDate: '2019/07/11',
    icon: '<i class=\'fa fa-2x fa-file-alt\'></i>' },
  { id: 185,
    name: 'Turpis porttitor',
    description:
     'Sed dolor nulla elit tellus. Et praesent elit elit nulla quam elit. Nulla vivamus quam cursus eu commodo praesent elit placerat interdum tincidunt. Egestas tincidunt. Nulla in adipiscing mi sollicitudin tellus feugiat adipiscing. Lorem vivamus praesent mi elit a feugiat porttitor nunc nulla non sem. Non sed elit sollicitudin porttitor lorem elit.',
    tags: [],
    access: [ 'joe' ],
    lastViewed: '2018/01/10',
    expirationDate: '2019/04/16',
    icon: '<i class=\'fa fa-2x fa-file-excel\'></i>' },
  { id: 523,
    name: 'Bibendum et nulla',
    description:
     'Mollis egestas et commodo vivamus a amet nibh. Interdum a. Sem dolor. Adipiscing luctus in interdum ipsum ac dolor et. Nulla nulla venenatis adipiscing interdum elit sit dolor.',
    tags: [ 'rhoncus' ],
    access: [ 'samantha' ],
    lastViewed: '2015/05/21',
    expirationDate: '2019/05/09',
    icon: '<i class=\'fa fa-2x fa-file-excel\'></i>' },
  { id: 169,
    name: 'Venenatis ut turpis egestas amet dolor',
    description:
     'Adipiscing gravida elit adipiscing amet a sollicitudin. Est bibendum quam ipsum adipiscing in a mollis amet elit.',
    tags: [ 'tincidunt' ],
    access: [ 'joe' ],
    lastViewed: '2014/10/09',
    expirationDate: '2019/10/21',
    icon: '<i class=\'fa fa-2x fa-file-powerpoint\'></i>' },
  { id: 458,
    name: 'Augue ac ipsum nulla',
    description:
     'Ut elit turpis sit elit mollis elit a nibh interdum porttitor nulla adipiscing tellus sem. Tellus egestas cursus feugiat mi lorem augue commodo adipiscing rhoncus. Cursus praesent ut elit. Eu in venenatis ac in praesent turpis a turpis. In quam interdum venenatis ut in in ut. Ipsum luctus placerat venenatis augue.',
    tags: [ 'cursus' ],
    access: [ 'mike' ],
    lastViewed: '2014/11/08',
    expirationDate: '2019/01/02',
    icon: '<i class=\'fa fa-2x fa-file-excel\'></i>' },
  { id: 3,
    name: 'Interdum elit placerat',
    description:
     'Turpis egestas interdum cursus elit nulla sollicitudin nibh luctus ut a sit. Ut placerat interdum sed eu quam sem mi amet nunc in adipiscing luctus turpis venenatis. Sit mollis mi nulla consectetur porttitor cursus amet vivamus adipiscing gravida commodo.',
    tags: [ 'mi', 'nulla' ],
    access: [ 'everyone' ],
    lastViewed: '2018/01/24',
    expirationDate: '2019/05/20',
    icon: '<i class=\'fa fa-2x fa-file-excel\'></i>' },
  { id: 771,
    name: 'Dolor elit adipiscing sem interdum',
    description:
     'Tincidunt in dolor elit elit in vivamus adipiscing placerat adipiscing in interdum amet cursus ipsum. A consectetur luctus interdum quam nunc nulla praesent bibendum.',
    tags: [ 'turpis', 'ut', 'nunc' ],
    access: [ 'everyone' ],
    lastViewed: '2017/06/06',
    expirationDate: '2019/10/21',
    icon: '<i class=\'fa fa-2x fa-file-excel\'></i>' },
  { id: 158,
    name: 'Lorem elit et amet',
    description:
     'Dolor gravida ut turpis mi. Egestas turpis eu lorem interdum. Et elit praesent a sed.',
    tags: [],
    access: [ 'joe' ],
    lastViewed: '2013/12/03',
    expirationDate: '2019/06/09',
    icon: '<i class=\'fa fa-2x fa-file-alt\'></i>' },
  { id: 649,
    name: 'Sit a eu mi elit vivamus',
    description:
     'Gravida est tincidunt sed gravida augue quam ut dolor tellus vivamus. Tellus adipiscing eu nibh elit adipiscing est consectetur amet elit sem adipiscing nunc. Commodo elit mollis ac porttitor in vivamus sit sollicitudin.',
    tags: [],
    access: [ 'everyone' ],
    lastViewed: '2018/07/24',
    expirationDate: '2019/02/02',
    icon: '<i class=\'fa fa-2x fa-file-powerpoint\'></i>' },
  { id: 452,
    name: 'Sem sed porttitor elit est adipiscing',
    description:
     'Elit in mi elit in tincidunt porttitor mollis. Luctus et mi rhoncus eu vivamus quam adipiscing feugiat in cursus consectetur.',
    tags: [],
    access: [ 'samantha' ],
    lastViewed: '2012/03/08',
    expirationDate: '2019/04/22',
    icon: '<i class=\'fa fa-2x fa-file-powerpoint\'></i>' },
  { id: 690,
    name: 'Sit in cursus lorem ipsum',
    description:
     'Sit interdum turpis porttitor adipiscing lorem non mollis rhoncus amet et placerat sollicitudin. Elit. Elit a praesent est tellus et. In. Elit a mollis in praesent lorem nibh.',
    tags: [ 'nunc', 'bibendum', 'eu' ],
    access: [ 'mike' ],
    lastViewed: '2016/09/16',
    expirationDate: '2019/11/27',
    icon: '<i class=\'fa fa-2x fa-file-alt\'></i>' },
  { id: 861,
    name: 'Quam sit luctus dolor ut ipsum',
    description:
     'Sit gravida elit et praesent. Mollis. Gravida. Amet commodo dolor sit eu elit. Praesent adipiscing sem et dolor tincidunt ut adipiscing sit in elit gravida est.',
    tags: [ 'porttitor', 'ut' ],
    access: [ 'joe' ],
    lastViewed: '2018/06/08',
    expirationDate: '2019/05/15',
    icon: '<i class=\'fa fa-2x fa-file-excel\'></i>' },
  { id: 385,
    name: 'Sed mollis bibendum placerat',
    description:
     'In lorem lorem vivamus. Est. Bibendum feugiat mollis venenatis dolor dolor nulla adipiscing sit sit ipsum elit praesent nibh. Feugiat. Cursus interdum bibendum nunc sit turpis tellus adipiscing amet porttitor ut a praesent. Lorem nulla consectetur sit in. A interdum dolor nunc.',
    tags: [ 'vivamus', 'ac' ],
    access: [ 'samantha' ],
    lastViewed: '2016/04/17',
    expirationDate: '2019/07/07',
    icon: '<i class=\'fa fa-2x fa-file-alt\'></i>' },
  { id: 717,
    name: 'Adipiscing gravida',
    description:
     'Dolor adipiscing amet amet. Ut a in dolor a bibendum. In quam elit non venenatis vivamus lorem ut elit mi adipiscing commodo praesent. Nulla in turpis in gravida nibh cursus praesent sed lorem. Quam nunc et venenatis tellus. Quam amet interdum sit.',
    tags: [ 'elit', 'mi' ],
    access: [ 'joe' ],
    lastViewed: '2015/10/14',
    expirationDate: '2019/07/30',
    icon: '<i class=\'fa fa-2x fa-file-powerpoint\'></i>' },
  { id: 52,
    name: 'Est amet consectetur adipiscing nibh',
    description:
     'Rhoncus sed amet adipiscing commodo consectetur elit mollis sit luctus amet est sit. In vivamus tincidunt praesent commodo luctus ut egestas venenatis mi ipsum.',
    tags: [ 'luctus' ],
    access: [ 'mike' ],
    lastViewed: '2013/11/14',
    expirationDate: '2019/11/22',
    icon: '<i class=\'fa fa-2x fa-file-powerpoint\'></i>' },
  { id: 516,
    name: 'Ut non lorem turpis',
    description:
     'Elit nulla gravida in adipiscing adipiscing ac ut elit adipiscing tincidunt feugiat nulla. Gravida ut. Eu cursus rhoncus lorem tellus nulla elit elit sollicitudin ipsum sed praesent et amet dolor. Mollis porttitor est tincidunt gravida turpis feugiat praesent consectetur nunc praesent. Consectetur praesent lorem in non elit in eu.',
    tags: [ 'adipiscing', 'mollis' ],
    access: [ 'everyone' ],
    lastViewed: '2014/10/19',
    expirationDate: '2019/03/19',
    icon: '<i class=\'fa fa-2x fa-file-word\'></i>' },
  { id: 740,
    name: 'Consectetur praesent adipiscing',
    description:
     'Ac sed turpis a in. Nulla adipiscing eu elit tincidunt venenatis consectetur. In in. Porttitor ut ut luctus sit ipsum turpis augue interdum. In ac non nulla amet ut dolor ut turpis commodo nunc egestas augue a. Adipiscing in vivamus cursus adipiscing elit sem gravida dolor. Placerat egestas nulla.',
    tags: [ 'augue' ],
    access: [ 'everyone' ],
    lastViewed: '2019/02/08',
    expirationDate: '2019/10/19',
    icon: '<i class=\'fa fa-2x fa-file-alt\'></i>' },
  { id: 402,
    name: 'Tellus mi',
    description:
     'Nibh. A et porttitor commodo sed cursus adipiscing eu sit ac turpis dolor mi. Praesent non in ut elit lorem. Venenatis adipiscing gravida sit lorem ut ipsum sem elit mi dolor tellus amet adipiscing. Tellus in a est ut. Turpis nunc mollis amet tellus interdum dolor a bibendum et consectetur. Ut venenatis dolor adipiscing elit egestas lorem elit tellus interdum elit ipsum turpis a.',
    tags: [ 'a', 'feugiat' ],
    access: [ 'samantha' ],
    lastViewed: '2018/08/01',
    expirationDate: '2019/09/19',
    icon: '<i class=\'fa fa-2x fa-file-alt\'></i>' },
  { id: 558,
    name: 'Feugiat tincidunt turpis',
    description:
     'Ut ipsum nunc nibh adipiscing amet lorem sollicitudin non in ac tincidunt in commodo. Tellus cursus praesent nulla in quam feugiat venenatis a elit placerat est. Interdum. Commodo lorem sed in feugiat interdum amet elit a nibh bibendum adipiscing. Non nunc in venenatis tincidunt sollicitudin elit elit adipiscing dolor turpis elit et nulla. Porttitor in adipiscing dolor elit nibh ipsum interdum.',
    tags: [],
    access: [ 'mike' ],
    lastViewed: '2015/09/25',
    expirationDate: '2019/11/21',
    icon: '<i class=\'fa fa-2x fa-file-word\'></i>' },
  { id: 463,
    name: 'Turpis sed luctus commodo est dolor adipiscing',
    description:
     'Nibh adipiscing ut tincidunt quam sem turpis interdum dolor tellus praesent est in elit consectetur. Gravida mi ipsum sit tincidunt nunc lorem dolor non adipiscing luctus. Feugiat cursus. Commodo eu tellus gravida elit turpis in ut in tincidunt mollis bibendum vivamus ut in. Gravida a elit. In luctus sed sit elit tincidunt adipiscing ipsum nulla gravida bibendum non porttitor est. Quam amet sit nulla lorem interdum mi adipiscing feugiat adipiscing dolor.',
    tags: [ 'adipiscing', 'amet', 'sem' ],
    access: [ 'mike' ],
    lastViewed: '2019/02/28',
    expirationDate: '2019/11/11',
    icon: '<i class=\'fa fa-2x fa-file-word\'></i>' },
  { id: 514,
    name: 'Praesent turpis est ut elit bibendum sed',
    description:
     'Gravida luctus amet dolor dolor est adipiscing elit egestas tellus gravida sem interdum adipiscing. Sit adipiscing praesent dolor commodo gravida nulla turpis amet ipsum amet mollis tincidunt consectetur praesent.',
    tags: [ 'nibh', 'adipiscing', 'mollis' ],
    access: [ 'mike' ],
    lastViewed: '2018/08/25',
    expirationDate: '2019/11/24',
    icon: '<i class=\'fa fa-2x fa-file-alt\'></i>' },
  { id: 362,
    name: 'Lorem mi amet elit mollis lorem',
    description:
     'A amet elit. In sollicitudin interdum. Mollis nunc. Sit sem vivamus mollis elit dolor. Ipsum ut luctus non sed vivamus porttitor mi et nulla nibh nunc. Adipiscing venenatis rhoncus turpis gravida sit gravida porttitor elit interdum sem. A sit rhoncus turpis in adipiscing sem nulla luctus vivamus.',
    tags: [ 'ut', 'elit', 'adipiscing' ],
    access: [ 'samantha' ],
    lastViewed: '2018/05/13',
    expirationDate: '2019/04/27',
    icon: '<i class=\'fa fa-2x fa-file-powerpoint\'></i>' },
  { id: 118,
    name: 'Venenatis sem tincidunt',
    description:
     'Ac ut et mollis eu dolor a gravida elit commodo nunc tincidunt adipiscing praesent praesent. Rhoncus adipiscing dolor. Elit elit dolor tincidunt. Turpis vivamus tellus sed sem quam non nulla lorem. Bibendum et elit sollicitudin. Praesent dolor ut ipsum praesent adipiscing tincidunt gravida placerat. Sit consectetur.',
    tags: [],
    access: [ 'mike' ],
    lastViewed: '2019/10/04',
    expirationDate: '2019/01/04',
    icon: '<i class=\'fa fa-2x fa-file-word\'></i>' },
  { id: 80,
    name: 'Ut nibh rhoncus vivamus praesent a',
    description:
     'Bibendum adipiscing adipiscing turpis nulla gravida eu elit nunc nibh turpis tellus in elit ipsum. Non feugiat ipsum amet interdum egestas est ut lorem elit.',
    tags: [ 'interdum' ],
    access: [ 'samantha' ],
    lastViewed: '2016/08/05',
    expirationDate: '2019/01/08',
    icon: '<i class=\'fa fa-2x fa-file-powerpoint\'></i>' },
  { id: 376,
    name: 'Gravida augue consectetur turpis in',
    description:
     'Non nulla vivamus gravida porttitor sed commodo elit tincidunt adipiscing lorem. Gravida elit elit amet praesent. Tellus ac elit turpis bibendum in dolor cursus luctus elit dolor.',
    tags: [ 'et' ],
    access: [ 'joe' ],
    lastViewed: '2016/12/21',
    expirationDate: '2019/09/08',
    icon: '<i class=\'fa fa-2x fa-file-alt\'></i>' },
  { id: 696,
    name: 'Elit mollis',
    description:
     'Et adipiscing. Mollis amet adipiscing feugiat a est elit dolor nibh tellus elit elit vivamus augue. Elit nulla dolor elit praesent nulla vivamus augue sit quam mollis ipsum. Ipsum elit quam in elit nulla augue bibendum lorem. Luctus porttitor quam ipsum.',
    tags: [ 'a' ],
    access: [ 'mike' ],
    lastViewed: '2013/05/06',
    expirationDate: '2019/10/26',
    icon: '<i class=\'fa fa-2x fa-file-excel\'></i>' },
  { id: 262,
    name: 'Adipiscing sollicitudin a elit nulla',
    description:
     'Augue turpis commodo. Nulla nibh gravida in ut bibendum tincidunt in quam elit placerat.',
    tags: [],
    access: [ 'mike' ],
    lastViewed: '2012/09/23',
    expirationDate: '2019/02/22',
    icon: '<i class=\'fa fa-2x fa-file-excel\'></i>' } ]